
import React from "react";


function getDistrictsArray(region)
{

    let districts = []
    switch(region){

        case "Jihočeský":

            districts = [
                'České Budějovice',
                'Český Krumlov',
                'Jindřichův Hradec',
                'Písek',
                'Prachatice',
                'Strakonice',
                'Tábor' ]



            break;

        case "Středočeský":

            districts = [
                'Benešov',
                'Beroun',
                'Kladno',
                'Kolín',
                'Kutná Hora',
                'Mělník',
                'Mladá Boleslav',
                'Nymburk',
                'Praha-východ',
                ' Praha-západ',
                'Příbram',
                'Rakovník',
            ]



            break;



        case "Plzeňský":

            districts = [
                'Domažlice',
                'Klatovy',
                'Plzeň-jih',
                'Plzeň-město',
                'Plzeň-sever',
                'Rokycany',
                'Tachov',
            ]



            break;

        case "Karlovarský":

            districts = [
                'Cheb',
                'Karlovy Vary',
                'Sokolov'
            ]



            break;

        case "Ústecký":

            districts = [
                'Děčín',
                'Chomutov',
                'Litoměřice',
                'Louny',
                'Most',
                'Teplice',
                'Ústí nad Labem'
            ]



            break;

        case "Královéhradecký":

            districts = [
                'Hradec Králové',
                'Jičín',
                'Náchod',
                'Rychnov nad Kněžnou',
                'Trutnov'
            ]



            break;

        case "Liberecký":

            districts = [
                'Česká Lípa',
                'Jablonec nad Nisou',
                'Liberec',
                'Semily',
            ]



            break;




        case "Pardubický":

            districts = [
                'Chrudim',
                'Pardubice',
                'Svitavy',
                'Ústí nad Orlicí'
            ]



            break;

        case "Vysočina":

            districts = [
                'Havlíčkův Brod',
                'Jihlava',
                'Pelhřimov',
                'Třebíč',
                'Žďár nad Sázavou'
            ]



            break;


        case "Jihomoravský":

            districts = [
                'Blansko',
                'Brno-město',
                'Brno-venkov',
                'Břeclav',
                'Hodonín',
                'Vyškov',
                'Znojmo'
            ]



            break;


        case "Olomoucký":

            districts = [
                'Jeseník',
                'Olomouc',
                'Prostějov',
                'Přerov',
                'Šumperk'
            ]



            break;



        case "Moravskoslezský":

            districts = [
                'Bruntál',
                'Frýdek-Místek',
                'Karviná',
                'Nový Jičín',
                'Opava',
                'Ostrava-město'
            ]



            break;

        case "Zlínský":

            districts = [
                'Kroměříž',
                'Uherské Hradiště',
                'Vsetín',
                'Zlín'
            ]



            break;














    }

    return districts;

}



export function getCitiesArray(district)
{

    let cities=[];


    switch (district) {


        case 'Benešov':

            cities=[

                'Benešov',
                'Bernartice',
                'Bílkovice',
                'Blažejovice',
                'Borovnice',
                'Bukovany',
                'Bystřice',
                'Ctiboř',
                'Čakov',
                'Čechtice',
                'Čerčany',
                'Červený Újezd',
                'Český Šternberk',
                'Čtyřkoly',
                'Děkanovice',
                'Divišov',
                'Dolní Kralovice',
                'Drahňovice',
                'Dunice',
                'Heřmaničky',
                'Hradiště',
                'Hulice',
                'Hvězdonice',
                'Chářovice',
                'Chleby',
                'Chlístov',
                'Chlum',
                'Chmelná',
                'Chocerady',
                'Choratice',
                'Chotýšany',
                'Chrášťany',
                'Jankov',
                'Javorník',
                'Ješetice',
                'Kamberk',
                'Keblov',
                'Kladruby',
                'Kondrac',
                'Kozmice',
                'Krhanice',
                'Krňany',
                'Křečovice',
                'Křivsoudov',
                'Kuňovice',
                'Lešany',
                'Libež',
                'Litichovice',
                'Loket',
                'Louňovice pod Blaníkem',
                'Lštění',
                'Maršovice',
                'Mezno',
                'Miličín',
                'Miřetice',
                'Mnichovice',
                'Mrač',
                'Načeradec',
                'Nespeky',
                'Netvořice',
                'Neustupov',
                'Neveklov',
                'Olbramovice',
                'Ostrov',
                'Ostředek',
                'Pavlovice',
                'Petroupim',
                'Popovice',
                'Poříčí nad Sázavou',
                'Postupice',
                'Pravonín',
                'Přestavlky u Čerčan',
                'Psáře',
                'Pyšely',
                'Rabyně',
                'Radošovice',
                'Rataje',
                'Ratměřice',
                'Řehenice',
                'Řimovice',
                'Sázava',
                'Slověnice',
                'Smilkov',
                'Snět',
                'Soběhrdy',
                'Soutice',
                'Stranný',
                'Strojetice',
                'Struhařov',
                'Střezimíř',
                'Studený',
                'Šetějovice',
                'Tehov',
                'Teplýšovice',
                'Tichonice',
                'Tisem',
                'Tomice',
                'Trhový Štěpánov',
                'Třebešice',
                'Týnec nad Sázavou',
                'Václavice',
                'Veliš',
                'Vlašim',
                'Vodslivy',
                'Vojkov',
                'Votice',
                'Vracovice',
                'Vranov',
                'Vrchotovy Janovice',
                'Všechlapy',
                'Vysoký Újezd',
                'Xaverov',
                'Zdislavice',
                'Zvěstov'




            ]

            break;

        case 'Beroun':
            cities=[

                'Bavoryně',
                'Beroun',
                'Běštín',
                'Broumy',
                'Březová',
                'Bubovice',
                'Bykoš',
                'Bzová',
                'Cerhovice',
                'Drozdov',
                'Felbabka',
                'Hlásná Třebaň',
                'Hořovice',
                'Hostomice',
                'Hředle',
                'Hudlice',
                'Hvozdec',
                'Hýskov',
                'Chaloupky',
                'Chlustina',
                'Chodouň',
                'Chrustenice',
                'Chyňava',
                'Jivina',
                'Karlštejn',
                'Komárov',
                'Koněprusy',
                'Korno',
                'Kotopeky',
                'Králův Dvůr',
                'Kublov',
                'Lážovice',
                'Lhotka',
                'Libomyšl',
                'Liteň',
                'Loděnice',
                'Lochovice',
                'Lužce',
                'Malá Víska',
                'Málkov',
                'Měňany',
                'Mezouň',
                'Mořina',
                'Mořinka',
                'Nenačovice',
                'Nesvačily',
                'Neumětely',
                'Nižbor',
                'Nový Jáchymov',
                'Olešná',
                'Osek',
                'Osov',
                'Otmíče',
                'Otročiněves',
                'Podbrdy',
                'Podluhy',
                'Praskolesy',
                'Rpety',
                'Skřipel',
                'Skuhrov',
                'Srbsko',
                'Stašov',
                'Suchomasty',
                'Svatá',
                'Svatý Jan pod Skalou',
                'Svinaře',
                'Tetín',
                'Tlustice',
                'Tmaň',
                'Točník',
                'Trubín',
                'Trubská',
                'Újezd',
                'Velký Chlumec',
                'Vinařice',
                'Vižina',
                'Vráž',
                'Všeradice',
                'Vysoký Újezd',
                'Zadní Třebaň',
                'Zaječov',
                'Záluží',
                'Zdice',
                'Žebrák',
                'Železná'

            ]
            break;

        case 'Kladno':
            cities=[
                'Běleč',
                'Běloky',
                'Beřovice',
                'Bílichov',
                'Blevice',
                'Brandýsek',
                'Braškov',
                'Bratronice',
                'Buštěhrad',
                'Cvrčovice',
                'Černuc',
                'Doksy',
                'Dolany',
                'Drnek',
                'Družec',
                'Dřetovice',
                'Dřínov',
                'Hobšovice',
                'Horní Bezděkov',
                'Hořešovice',
                'Hořešovičky',
                'Hospozín',
                'Hostouň',
                'Hradečno',
                'Hrdlív',
                'Hřebeč',
                'Chržín',
                'Jarpice',
                'Jedomělice',
                'Jemníky',
                'Kačice',
                'Kamenné Žehrovice',
                'Kamenný Most',
                'Kladno',
                'Klobuky',
                'Kmetiněves',
                'Knovíz',
                'Koleč',
                'Královice',
                'Kutrovice',
                'Kvílice',
                'Kyšice',
                'Lány',
                'Ledce',
                'Lhota',
                'Libochovičky',
                'Libovice',
                'Libušín',
                'Lidice',
                'Líský',
                'Loucká',
                'Makotřasy',
                'Malé Kyšice',
                'Malé Přítočno',
                'Malíkovice',
                'Neprobylice',
                'Neuměřice',
                'Otvovice',
                'Páleč',
                'Pavlov',
                'Pchery',
                'Pletený Újezd',
                'Plchov',
                'Podlešín',
                'Poštovice',
                'Pozdeň',
                'Přelíc',
                'Řisuty',
                'Sazená',
                'Slaný',
                'Slatina',
                'Smečno',
                'Stehelčeves',
                'Stochov',
                'Stradonice',
                'Studeněves',
                'Svárov',
                'Svinařov',
                'Šlapanice',
                'Třebichovice',
                'Třebíz',
                'Třebusice',
                'Tuchlovice',
                'Tuřany',
                'Uhy',
                'Unhošť',
                'Velká Dobrá',
                'Velké Přítočno',
                'Velvary',
                'Vinařice',
                'Vraný',
                'Vrbičany',
                'Zájezd',
                'Zákolany',
                'Zichovec',
                'Zlonice',
                'Zvoleněves',
                'Želenice',
                'Žilina',
                'Žižice'


            ]
            break;

        case 'Kolín':
            cities=[
                'Barchovice',
                'Bečváry',
                'Bělušice',
                'Břežany I',
                'Břežany II',
                'Býchory',
                'Cerhenice',
                'Církvice',
                'Černíky',
                'Červené Pečky',
                'Český Brod',
                'Dobřichov',
                'Dolní Chvatliny',
                'Dománovice',
                'Doubravčice',
                'Drahobudice',
                'Grunta',
                'Horní Kruty',
                'Hradešín',
                'Choťovice',
                'Chotutice',
                'Chrášťany',
                'Jestřabí Lhota',
                'Kbel',
                'Klášterní Skalice',
                'Klučov',
                'Kolín',
                'Konárovice',
                'Kořenice',
                'Kouřim',
                'Krakovany',
                'Krupá',
                'Krychnov',
                'Křečhoř',
                'Kšely',
                'Libenice',
                'Libodřice',
                'Lipec',
                'Lošany',
                'Malotice',
                'Masojedy',
                'Mrzky',
                'Nebovidy',
                'Němčice',
                'Nová Ves I',
                'Ohaře',
                'Ovčáry',
                'Pašinka',
                'Pečky',
                'Plaňany',
                'Pňov-Předhradí',
                'Polepy',
                'Polní Chrčice',
                'Polní Voděrady',
                'Poříčany',
                'Přehvozdí',
                'Přistoupim',
                'Přišimasy',
                'Radim',
                'Radovesnice I',
                'Radovesnice II',
                'Ratboř',
                'Ratenice',
                'Rostoklaty',
                'Skvrňov',
                'Starý Kolín',
                'Svojšice',
                'Tatce',
                'Tismice',
                'Toušice',
                'Třebovle',
                'Tři Dvory',
                'Tuchoraz',
                'Tuklaty',
                'Týnec nad Labem',
                'Uhlířská Lhota',
                'Veletov',
                'Velim',
                'Velký Osek',
                'Veltruby',
                'Vitice',
                'Volárna',
                'Vrátkov',
                'Vrbčany',
                'Zalešany',
                'Zásmuky',
                'Žabonosy',
                'Ždánice',
                'Žehuň',
                'Žiželice'

            ]
            break;

        case 'Kutná Hora':
            cities=[
                'Adamov',
                'Bernardov',
                'Bílé Podolí',
                'Bludov',
                'Bohdaneč',
                'Brambory',
                'Bratčice',
                'Církvice',
                'Čáslav',
                'Čejkovice',
                'Černíny',
                'Červené Janovice',
                'Čestín',
                'Dobrovítov',
                'Dolní Pohleď',
                'Drobovice',
                'Hlízov',
                'Horka I',
                'Horka II',
                'Horky',
                'Horušice',
                'Hostovlice',
                'Hraběšín',
                'Chabeřice',
                'Chlístovice',
                'Chotusice',
                'Kácov',
                'Kluky',
                'Kobylnice',
                'Košice',
                'Krchleby',
                'Křesetice',
                'Kutná Hora',
                'Ledečko',
                'Malešov',
                'Miskovice',
                'Močovice',
                'Nepoměřice',
                'Nové Dvory',
                'Okřesaneč',
                'Onomyšl',
                'Opatovice I',
                'Paběnice',
                'Pertoltice',
                'Petrovice I',
                'Petrovice II',
                'Podveky',
                'Potěhy',
                'Rašovice',
                'Rataje nad Sázavou',
                'Rohozec',
                'Řendějov',
                'Samopše',
                'Semtěš',
                'Schořov',
                'Slavošov',
                'Soběšín',
                'Souňov',
                'Staňkovice',
                'Starkoč',
                'Sudějov',
                'Suchdol',
                'Svatý Mikuláš',
                'Šebestěnice',
                'Štipoklasy',
                'Třebešice',
                'Třebětín',
                'Třebonín',
                'Tupadly',
                'Uhlířské Janovice',
                'Úmonín',
                'Úžice',
                'Vavřinec',
                'Vidice',
                'Vinaře',
                'Vlačice',
                'Vlastějovice',
                'Vlkaneč',
                'Vodranty',
                'Vrdy',
                'Záboří nad Labem',
                'Zbizuby',
                'Zbraslavice',
                'Zbýšov',
                'Zruč nad Sázavou',
                'Žáky',
                'Žehušice',
                'Žleby'



            ]
            break;

        case 'Mělník':
            cities=[
                'Býkev',
                'Byšice',
                'Cítov',
                'Čakovičky',
                'Čečelice',
                'Dobřeň',
                'Dolany nad Vltavou',
                'Dolní Beřkovice',
                'Dolní Zimoř',
                'Dřínov',
                'Horní Počaply',
                'Hořín',
                'Hostín u Vojkovic',
                'Hostín',
                'Chlumín',
                'Chorušice',
                'Chvatěruby',
                'Jeviněves',
                'Kadlín',
                'Kanina',
                'Kly',
                'Kojetice',
                'Kokořín',
                'Kostelec nad Labem',
                'Kozomín',
                'Kralupy nad Vltavou',
                'Ledčice',
                'Lhotka',
                'Liběchov',
                'Libiš',
                'Liblice',
                'Lobeč',
                'Lužec nad Vltavou',
                'Malý Újezd',
                'Medonosy',
                'Mělnické Vtelno',
                'Mělník',
                'Mšeno',
                'Nebužely',
                'Nedomice',
                'Nelahozeves',
                'Neratovice',
                'Nosálov',
                'Nová Ves',
                'Obříství',
                'Olovnice',
                'Ovčáry',
                'Postřižín',
                'Řepín',
                'Spomyšl',
                'Stránka',
                'Střemy',
                'Tišice',
                'Tuhaň',
                'Tupadly',
                'Újezdec',
                'Úžice',
                'Velký Borek',
                'Veltrusy',
                'Vidim',
                'Vojkovice',
                'Vraňany',
                'Všestudy',
                'Všetaty',
                'Vysoká',
                'Zálezlice',
                'Zlončice',
                'Zlosyň',
                'Želízy'



            ]
            break;

        case 'Mladá Boleslav':

            cities=[
                'Bakov nad Jizerou',
                'Bělá pod Bezdězem',
                'Benátky nad Jizerou',
                'Bezno',
                'Bílá Hlína',
                'Bítouchov',
                'Boreč',
                'Boseň',
                'Bradlec',
                'Branžež',
                'Brodce',
                'Březina',
                'Březno',
                'Březovice',
                'Bukovno',
                'Ctiměřice',
                'Čachovice',
                'Čistá',
                'Dalovice',
                'Dlouhá Lhota',
                'Dobrovice',
                'Dobšín',
                'Dolní Bousov',
                'Dolní Krupá',
                'Dolní Slivno',
                'Dolní Stakory',
                'Domousnice',
                'Doubravička',
                'Horky nad Jizerou',
                'Horní Bukovina',
                'Horní Slivno',
                'Hrdlořezy',
                'Hrušov',
                'Husí Lhota',
                'Charvatce',
                'Chocnějovice',
                'Chotětov',
                'Chudíř',
                'Jabkenice',
                'Jivina',
                'Jizerní Vtelno',
                'Josefův Důl',
                'Katusice',
                'Klášter Hradiště nad Jizerou',
                'Kluky',
                'Kněžmost',
                'Kobylnice',
                'Kochánky',
                'Kolomuty',
                'Koryta',
                'Kosmonosy',
                'Kosořice',
                'Košátky',
                'Kováň',
                'Kovanec',
                'Krásná Ves',
                'Krnsko',
                'Kropáčova Vrutice',
                'Ledce',
                'Lhotky',
                'Lipník',
                'Loukov',
                'Loukovec',
                'Luštěnice',
                'Mečeříž',
                'Mladá Boleslav',
                'Mnichovo Hradiště',
                'Mohelnice nad Jizerou',
                'Mukařov',
                'Němčice',
                'Nemyslovice',
                'Nepřevázka',
                'Neveklovice',
                'Niměřice',
                'Nová Telib',
                'Nová Ves u Bakova',
                'Obrubce',
                'Obruby',
                'Pěčice',
                'Pětikozly',
                'Petkovy',
                'Písková Lhota',
                'Plazy',
                'Plužná',
                'Prodašice',
                'Předměřice nad Jizerou',
                'Přepeře',
                'Ptýrov',
                'Rabakov',
                'Rohatsko',
                'Rokytá',
                'Rokytovec',
                'Řepov',
                'Řitonice',
                'Sedlec',
                'Semčice',
                'Sezemice',
                'Skalsko',
                'Skorkov',
                'Smilovice',
                'Sojovice',
                'Sovínky',
                'Strašnov',
                'Strážiště',
                'Strenice',
                'Sudoměř',
                'Sukorady',
                'Tuřice',
                'Ujkovice',
                'Velké Všelisy',
                'Veselice',
                'Vinařice',
                'Vinec',
                'Vlkava',
                'Vrátno',
                'Všejany',
                'Zdětín',
                'Žďár',
                'Žerčice',
                'Židněves'



            ]
            break;

        case 'Nymburk':
            cities=[
                'Běrunice',
                'Bobnice',
                'Bříství',
                'Budiměřice',
                'Čilec',
                'Činěves',
                'Dlouhopolsko',
                'Dobšice',
                'Dvory',
                'Dymokury',
                'Hořany',
                'Hořátev',
                'Hradčany',
                'Hradištko',
                'Hrubý Jeseník',
                'Chleby',
                'Choťánky',
                'Chotěšice',
                'Chrást',
                'Chroustov',
                'Jíkev',
                'Jiřice',
                'Jizbice',
                'Kamenné Zboží',
                'Kněžice',
                'Kněžičky',
                'Kolaje',
                'Kostelní Lhota',
                'Kostomlátky',
                'Kostomlaty nad Labem',
                'Košík',
                'Kounice',
                'Kouty',
                'Kovanice',
                'Krchleby',
                'Křečkov',
                'Křinec',
                'Libice nad Cidlinou',
                'Loučeň',
                'Lysá nad Labem',
                'Mcely',
                'Městec Králové',
                'Milčice',
                'Milovice',
                'Netřebice',
                'Nový Dvůr',
                'Nymburk',
                'Odřepsy',
                'Okřínek',
                'Opočnice',
                'Opolany',
                'Oseček',
                'Oskořínek',
                'Ostrá',
                'Pátek',
                'Písková Lhota',
                'Písty',
                'Poděbrady',
                'Podmoky',
                'Přerov nad Labem',
                'Rožďalovice',
                'Sadská',
                'Sány',
                'Seletice',
                'Semice',
                'Senice',
                'Sloveč',
                'Sokoleč',
                'Stará Lysá',
                'Starý Vestec',
                'Straky',
                'Stratov',
                'Třebestovice',
                'Úmyslovice',
                'Velenice',
                'Velenka',
                'Vestec',
                'Vlkov pod Oškobrhem',
                'Vrbice',
                'Vrbová Lhota',
                'Všechlapy',
                'Vykáň',
                'Záhornice',
                'Zbožíčko',
                'Zvěřínek',
                'Žitovlice'


            ]
            break;

        case 'Praha-východ':

            cities=[
                'Babice',
                'Bašť',
                'Borek',
                'Bořanovice',
                'Brandýs nad Labem',
                'Brázdim',
                'Březí',
                'Čelákovice',
                'Černé Voděrady',
                'Čestlice',
                'Dobročovice',
                'Dobřejovice',
                'Doubek',
                'Dřevčice',
                'Dřísy',
                'Herink',
                'Hlavenec',
                'Horoušany',
                'Hovorčovice',
                'Hrusice',
                'Husinec',
                'Jenštejn',
                'Jevany',
                'Jirny',
                'Kaliště',
                'Kamenice',
                'Káraný',
                'Klecany',
                'Klíčany',
                'Klokočná',
                'Konětopy',
                'Konojedy',
                'Kostelec nad Černými lesy',
                'Kostelec u Křížků',
                'Kostelní Hlavno',
                'Kozojedy',
                'Křenek',
                'Křenice',
                'Křížkový Újezdec',
                'Kunice',
                'Květnice',
                'Lázně Toušeň',
                'Lhota',
                'Líbeznice',
                'Louňovice',
                'Máslovice',
                'Měšice',
                'Mirošovice',
                'Mnichovice',
                'Modletice',
                'Mochov',
                'Mratín',
                'Mukařov',
                'Nehvizdy',
                'Nová Ves',
                'Nový Vestec',
                'Nučice',
                'Nupaky',
                'Odolena Voda',
                'Oleška',
                'Ondřejov',
                'Oplany',
                'Panenské Břežany',
                'Pětihosty',
                'Petříkov',
                'Podolanka',
                'Polerady',
                'Popovičky',
                'Prusice',
                'Předboj',
                'Přezletice',
                'Radějovice',
                'Radonice',
                'Říčany',
                'Sedlec',
                'Senohraby',
                'Sibřina',
                'Sluhy',
                'Sluštice',
                'Strančice',
                'Struhařov',
                'Stříbrná Skalice',
                'Sudovo Hlavno',
                'Sulice',
                'Svémyslice',
                'Světice',
                'Svojetice',
                'Šestajovice',
                'Škvorec',
                'Štíhlice',
                'Tehov',
                'Tehovec',
                'Úvaly',
                'Veleň',
                'Veliká Ves',
                'Velké Popovice',
                'Větrušice',
                'Vlkančice',
                'Vodochody',
                'Všestary',
                'Vyšehořovice',
                'Výžerky',
                'Vyžlovka',
                'Zápy',
                'Záryby',
                'Zdiby',
                'Zeleneč',
                'Zlatá',
                'Zlonín',
                'Zvánovice'


            ]
            break;

        case 'Praha-západ':
            cities=[
                'Bojanovice',
                'Bratřínov',
                'Březová-Oleško',
                'Buš',
                'Černolice',
                'Černošice',
                'Červený Újezd',
                'Číčovice',
                'Čisovice',
                'Davle',
                'Dobrovíz',
                'Dobříč',
                'Dobřichovice',
                'Dolní Břežany',
                'Drahelčice',
                'Holubice',
                'Horoměřice',
                'Hostivice',
                'Hradištko',
                'Hvozdnice',
                'Choteč',
                'Chrášťany',
                'Chýně',
                'Chýnice',
                'Jeneč',
                'Jesenice',
                'Jílové u Prahy',
                'Jíloviště',
                'Jinočany',
                'Kamenný Přívoz',
                'Karlík',
                'Klínec',
                'Kněževes',
                'Kosoř',
                'Kytín',
                'Lety',
                'Libčice nad Vltavou',
                'Libeř',
                'Lichoceves',
                'Líšnice',
                'Měchenice',
                'Mníšek pod Brdy',
                'Nučice',
                'Ohrobec',
                'Okoř',
                'Okrouhlo',
                'Ořech',
                'Petrov',
                'Pohoří',
                'Průhonice',
                'Psáry',
                'Ptice',
                'Roblín',
                'Roztoky',
                'Rudná',
                'Řevnice',
                'Řitka',
                'Slapy',
                'Statenice',
                'Středokluky',
                'Svrkyně',
                'Štěchovice',
                'Tachlovice',
                'Trnová',
                'Třebotov',
                'Tuchoměřice',
                'Tursko',
                'Úholičky',
                'Úhonice',
                'Únětice',
                'Velké Přílepy',
                'Vestec',
                'Vonoklasy',
                'Vrané nad Vltavou',
                'Všenory',
                'Zahořany',
                'Zbuzany',
                'Zlatníky-Hodkovice',
                'Zvole'


            ]
            break;

        case 'Příbram':
            cities=[
                'Bezděkov pod Třemšínem',
                'Bohostice',
                'Bohutín',
                'Borotice',
                'Bratkovice',
                'Březnice',
                'Buková u Příbramě',
                'Bukovany',
                'Cetyně',
                'Čenkov',
                'Čím',
                'Daleké Dušníky',
                'Dlouhá Lhota',
                'Dobříš',
                'Dolní Hbity',
                'Drahenice',
                'Drahlín',
                'Drásov',
                'Drevníky',
                'Drhovy',
                'Dubenec',
                'Dublovice',
                'Dubno',
                'Háje',
                'Hluboš',
                'Hlubyně',
                'Horčápsko',
                'Hřiměždice',
                'Hudčice',
                'Hvožďany',
                'Chotilsko',
                'Chrást',
                'Chraštice',
                'Jablonná',
                'Jesenice',
                'Jince',
                'Kamýk nad Vltavou',
                'Klučenice',
                'Kňovice',
                'Korkyně',
                'Kosova Hora',
                'Kotenčice',
                'Koupě',
                'Kozárovice',
                'Krásná Hora nad Vltavou',
                'Křepenice',
                'Křešín',
                'Láz',
                'Lazsko',
                'Lešetice',
                'Lhota u Příbramě',
                'Malá Hraštice',
                'Milešov',
                'Milín',
                'Modřovice',
                'Mokrovraty',
                'Nalžovice',
                'Narysov',
                'Nečín',
                'Nedrahovice',
                'Nechvalice',
                'Nepomuk',
                'Nestrašovice',
                'Nová Ves pod Pleší',
                'Nové Dvory',
                'Nový Knín',
                'Občov',
                'Obecnice',
                'Obory',
                'Obořiště',
                'Ohrazenice',
                'Osečany',
                'Ostrov',
                'Ouběnice',
                'Pečice',
                'Petrovice',
                'Pičín',
                'Počaply',
                'Počepice',
                'Podlesí',
                'Prosenická Lhota',
                'Příbram',
                'Příčovy',
                'Radětice',
                'Radíč',
                'Rosovice',
                'Rožmitál pod Třemšínem',
                'Rybníky',
                'Sádek',
                'Sedlčany',
                'Sedlec-Prčice',
                'Sedlice',
                'Smolotely',
                'Solenice',
                'Stará Huť',
                'Starosedlský Hrádek',
                'Suchodol',
                'Svaté Pole',
                'Svatý Jan',
                'Svojšice',
                'Štětkovice',
                'Těchařovice',
                'Tochovice',
                'Trhové Dušníky',
                'Třebsko',
                'Tušovice',
                'Velká Lečice',
                'Věšín',
                'Višňová',
                'Volenice',
                'Voznice',
                'Vrančice',
                'Vranovice',
                'Vševily',
                'Vysoká u Příbramě',
                'Vysoký Chlumec',
                'Zalužany',
                'Zbenice',
                'Zduchovice',
                'Županovice'


            ]
            break;

        case 'Rakovník':
            cities=[
                'Bdín',
                'Branov',
                'Břežany',
                'Čistá',
                'Děkov',
                'Drahouš',
                'Hořesedly',
                'Hořovičky',
                'Hracholusky',
                'Hřebečníky',
                'Hředle',
                'Hvozd',
                'Chrášťany',
                'Janov',
                'Jesenice',
                'Kalivody',
                'Karlova Ves',
                'Kněževes',
                'Kolešov',
                'Kolešovice',
                'Kounov',
                'Kozojedy',
                'Krakov',
                'Krakovec',
                'Kroučová',
                'Krty',
                'Krupá',
                'Krušovice',
                'Křivoklát',
                'Lašovice',
                'Lišany',
                'Lubná',
                'Lužná',
                'Malinová',
                'Městečko',
                'Milostín',
                'Milý',
                'Mšec',
                'Mšecké Žehrovice',
                'Mutějovice',
                'Nesuchyně',
                'Nezabudice',
                'Nové Strašecí',
                'Nový Dům',
                'Olešná',
                'Oráčov',
                'Panoší Újezd',
                'Pavlíkov',
                'Petrovice',
                'Pochvalov',
                'Přerubenice',
                'Příčina',
                'Přílepy',
                'Pšovlky',
                'Pustověty',
                'Račice',
                'Rakovník',
                'Roztoky',
                'Ruda',
                'Rynholec',
                'Řeřichy',
                'Řevničov',
                'Senec',
                'Senomaty',
                'Skryje',
                'Slabce',
                'Smilovice',
                'Srbeč',
                'Svojetín',
                'Sýkořice',
                'Šanov',
                'Šípy',
                'Švihov',
                'Třeboc',
                'Třtice',
                'Václavy',
                'Velká Buková',
                'Velká Chmelištná',
                'Všesulov',
                'Všetaty',
                'Zavidov',
                'Zbečno',
                'Žďár'


            ]
            break;


        case 'České Budějovice':
            cities=[
                'Adamov',
                'Bečice',
                'Borek',
                'Borovany',
                'Borovnice',
                'Boršov nad Vltavou',
                'Bošilec',
                'Branišov',
                'Břehov',
                'Čakov',
                'Čejkovice',
                'Čenkov u Bechyně',
                'České Budějovice',
                'Čížkrajice',
                'Dasný',
                'Dívčice',
                'Dobrá Voda u Českých Budějovic',
                'Dobšice',
                'Dolní Bukovsko',
                'Doubravice',
                'Doudleby',
                'Drahotěšice',
                'Dražíč',
                'Dříteň',
                'Dubičné',
                'Dubné',
                'Dynín',
                'Habří',
                'Hartmanice',
                'Heřmaň',
                'Hlavatce',
                'Hlincová Hora',
                'Hluboká nad Vltavou',
                'Homole',
                'Horní Kněžeklady',
                'Horní Stropnice',
                'Hosín',
                'Hosty',
                'Hradce',
                'Hranice',
                'Hrdějovice',
                'Hůry',
                'Hvozdec',
                'Chotýčany',
                'Chrášťany',
                'Jankov',
                'Jílovice',
                'Jivno',
                'Kamenná',
                'Kamenný Újezd',
                'Komařice',
                'Kvítkovice',
                'Ledenice',
                'Libín',
                'Libníč',
                'Lipí',
                'Lišov',
                'Litvínovice',
                'Ločenice',
                'Mazelov',
                'Mladošovice',
                'Modrá Hůrka',
                'Mokrý Lom',
                'Mydlovary',
                'Nákří',
                'Nedabyle',
                'Neplachov',
                'Nová Ves',
                'Nové Hrady',
                'Olešnice',
                'Olešník',
                'Ostrolovský Újezd',
                'Petříkov',
                'Pištín',
                'Planá',
                'Plav',
                'Radošovice',
                'Roudné',
                'Rudolfov',
                'Římov',
                'Sedlec',
                'Slavče',
                'Srubec',
                'Staré Hodějovice',
                'Strážkovice',
                'Strýčice',
                'Střížov',
                'Svatý Jan nad Malší',
                'Ševětín',
                'Štěpánovice',
                'Temelín',
                'Trhové Sviny',
                'Týn nad Vltavou',
                'Úsilné',
                'Včelná',
                'Vidov',
                'Vitín',
                'Vlkov',
                'Vrábče',
                'Vráto',
                'Všemyslice',
                'Záboří',
                'Zahájí',
                'Závraty',
                'Zliv',
                'Zvíkov',
                'Žabovřesky',
                'Žár',
                'Žimutice'


            ]

            break;


        case 'Český Krumlov':
            cities=[
                'Benešov nad Černou',
                'Besednice',
                'Bohdalovice',
                'Brloh',
                'Bujanov',
                'Černá v Pošumaví',
                'Český Krumlov',
                'Dolní Dvořiště',
                'Dolní Třebonín',
                'Frymburk',
                'Holubov',
                'Horní Dvořiště',
                'Horní Planá',
                'Hořice na Šumavě',
                'Chlumec',
                'Chvalšiny',
                'Kájov',
                'Kaplice',
                'Křemže',
                'Lipno nad Vltavou',
                'Loučovice',
                'Malonty',
                'Malšín',
                'Mirkovice',
                'Mojné',
                'Netřebice',
                'Nová Ves',
                'Omlenice',
                'Pohorská Ves',
                'Polná na Šumavě',
                'Přední Výtoň',
                'Přídolí',
                'Přísečná',
                'Rožmberk nad Vltavou',
                'Rožmitál na Šumavě',
                'Soběnov',
                'Srnín',
                'Střítež',
                'Světlík',
                'Velešín',
                'Větřní',
                'Věžovatá Pláně',
                'Vyšší Brod',
                'Zlatá Koruna',
                'Zubčice',
                'Zvíkov'

            ]

            break;

        case 'Jindřichův Hradec':
            cities=[
                'Báňovice',
                'Bednárec',
                'Bednáreček',
                'Blažejov',
                'Bořetín',
                'Březina',
                'Budeč',
                'Budíškovice',
                'Cep',
                'Cizkrajov',
                'Červený Hrádek',
                'České Velenice',
                'Český Rudolec',
                'Číměř',
                'Člunek',
                'Dačice',
                'Dešná',
                'Deštná',
                'Dívčí Kopy',
                'Dobrohošť',
                'Dolní Pěna',
                'Dolní Žďár',
                'Domanín',
                'Doňov',
                'Drunče',
                'Dunajovice',
                'Dvory nad Lužnicí',
                'Frahelž',
                'Hadravova Rosička',
                'Halámky',
                'Hamr',
                'Hatín',
                'Heřmaneč',
                'Horní Meziříčko',
                'Horní Němčice',
                'Horní Pěna',
                'Horní Radouň',
                'Horní Skrýchov',
                'Horní Slatina',
                'Hospříz',
                'Hrachoviště',
                'Hříšice',
                'Chlum u Třeboně',
                'Jarošov nad Nežárkou',
                'Jilem',
                'Jindřichův Hradec',
                'Kačlehy',
                'Kamenný Malíkov',
                'Kardašova Řečice',
                'Klec',
                'Kostelní Radouň',
                'Kostelní Vydří',
                'Kunžak',
                'Lásenice',
                'Lodhéřov',
                'Lomnice nad Lužnicí',
                'Lužnice',
                'Majdalena',
                'Nová Bystřice',
                'Nová Olešná',
                'Nová Včelnice',
                'Nová Ves nad Lužnicí',
                'Novosedly nad Nežárkou',
                'Okrouhlá Radouň',
                'Peč',
                'Písečné',
                'Pístina',
                'Plavsko',
                'Pleše',
                'Pluhův Žďár',
                'Polště',
                'Ponědraž',
                'Ponědrážka',
                'Popelín',
                'Příbraz',
                'Rapšach',
                'Ratiboř',
                'Rodvínov',
                'Roseč',
                'Rosička',
                'Slavonice',
                'Smržov',
                'Staňkov',
                'Staré Hobzí',
                'Staré Město pod Landštejnem',
                'Stráž nad Nežárkou',
                'Strmilov',
                'Stříbřec',
                'Střížovice',
                'Studená',
                'Suchdol nad Lužnicí',
                'Světce',
                'Třebětice',
                'Třeboň',
                'Újezdec',
                'Velký Ratmírov',
                'Vícemil',
                'Višňová',
                'Vlčetínec',
                'Volfířov',
                'Vydří',
                'Záblatí',
                'Záhoří',
                'Zahrádky',
                'Žďár',
                'Županovice'


            ]

            break;

        case 'Písek':
            cities=[
                'Albrechtice nad Vltavou',
                'Bernartice',
                'Borovany',
                'Boudy',
                'Božetice',
                'Branice',
                'Cerhonice',
                'Čimelice',
                'Čížová',
                'Dobev',
                'Dolní Novosedly',
                'Drhovle',
                'Heřmaň',
                'Horosedly',
                'Hrazany',
                'Hrejkovice',
                'Chyšky',
                'Jetětice',
                'Jickovice',
                'Kestřany',
                'Kluky',
                'Kostelec nad Vltavou',
                'Kovářov',
                'Kožlí',
                'Králova Lhota',
                'Křenovice',
                'Křižanov',
                'Kučeř',
                'Květov',
                'Lety',
                'Milevsko',
                'Minice',
                'Mirotice',
                'Mirovice',
                'Mišovice',
                'Myslín',
                'Nerestce',
                'Nevězice',
                'Okrouhlá',
                'Olešná',
                'Orlík nad Vltavou',
                'Osek',
                'Oslov',
                'Ostrovec',
                'Paseky',
                'Písek',
                'Podolí I',
                'Probulov',
                'Protivín',
                'Přeborov',
                'Předotice',
                'Přeštěnice',
                'Putim',
                'Rakovice',
                'Ražice',
                'Sepekov',
                'Skály',
                'Slabčice',
                'Smetanova Lhota',
                'Stehlovice',
                'Tálín',
                'Temešvár',
                'Varvažov',
                'Veselíčko',
                'Vlastec',
                'Vlksice',
                'Vojníkov',
                'Vráž',
                'Vrcovice',
                'Záhoří',
                'Zbelítov',
                'Zběšičky',
                'Zhoř',
                'Zvíkovské Podhradí',
                'Žďár'


            ]

            break;

        case 'Prachatice':
            cities=[
                'Babice',
                'Bohumilice',
                'Bohunice',
                'Borová Lada',
                'Bošice',
                'Budkov',
                'Buk',
                'Bušanovice',
                'Čkyně',
                'Drslavice',
                'Dub',
                'Dvory',
                'Horní Vltavice',
                'Hracholusky',
                'Husinec',
                'Chlumany',
                'Chroboly',
                'Chvalovice',
                'Kratušín',
                'Křišťanov',
                'Ktiš',
                'Kubova Huť',
                'Kvilda',
                'Lažiště',
                'Lčovice',
                'Lenora',
                'Lhenice',
                'Lipovice',
                'Lužice',
                'Mahouš',
                'Malovice',
                'Mičovice',
                'Nebahovy',
                'Němčice',
                'Netolice',
                'Nicov',
                'Nová Pec',
                'Nové Hutě',
                'Olšovice',
                'Pěčnov',
                'Prachatice',
                'Radhostice',
                'Stachy',
                'Stožec',
                'Strážný',
                'Strunkovice nad Blanicí',
                'Svatá Maří',
                'Šumavské Hoštice',
                'Těšovice',
                'Tvrzice',
                'Újezdec',
                'Vacov',
                'Vimperk',
                'Vitějovice',
                'Vlachovo Březí',
                'Volary',
                'Vrbice',
                'Záblatí',
                'Zábrdí',
                'Zálezly',
                'Zbytiny',
                'Zdíkov',
                'Žárovná',
                'Želnava',
                'Žernovice'


            ]

            break;

        case 'Strakonice':
            cities=[

                'Bavorov',
                'Bělčice',
                'Bezdědovice',
                'Bílsko',
                'Blatná',
                'Bratronice',
                'Březí',
                'Budyně',
                'Buzice',
                'Cehnice',
                'Čečelovice',
                'Čejetice',
                'Čepřovice',
                'Čestice',
                'Číčenice',
                'Doubravice',
                'Drahonice',
                'Drachkov',
                'Drážov',
                'Droužetice',
                'Dřešín',
                'Hajany',
                'Hájek',
                'Hlupín',
                'Horní Poříčí',
                'Hornosín',
                'Hoslovice',
                'Hoštice',
                'Chelčice',
                'Chlum',
                'Chobot',
                'Chrášťovice',
                'Jinín',
                'Kadov',
                'Kalenice',
                'Katovice',
                'Kladruby',
                'Kocelovice',
                'Krajníčko',
                'Kraselov',
                'Krašlovice',
                'Krejnice',
                'Krty-Hradec',
                'Kuřimany',
                'Kváskovice',
                'Lažánky',
                'Lažany',
                'Libějovice',
                'Libětice',
                'Litochovice',
                'Lnáře',
                'Lom',
                'Mačkov',
                'Malenice',
                'Mečichov',
                'Měkynec',
                'Milejovice',
                'Miloňovice',
                'Mnichov',
                'Mutěnice',
                'Myštice',
                'Nebřehovice',
                'Němčice',
                'Němětice',
                'Nihošovice',
                'Nišovice',
                'Nová Ves',
                'Novosedly',
                'Osek',
                'Paračov',
                'Pivkovice',
                'Pohorovice',
                'Pracejovice',
                'Předmíř',
                'Přední Zborovice',
                'Předslavice',
                'Přechovice',
                'Přešťovice',
                'Radějovice',
                'Radomyšl',
                'Radošovice',
                'Rovná',
                'Řepice',
                'Sedlice',
                'Skály',
                'Skočice',
                'Slaník',
                'Sousedovice',
                'Stožice',
                'Strakonice',
                'Strašice',
                'Strunkovice nad Volyňkou',
                'Střelské Hoštice',
                'Škvořetice',
                'Štěchovice',
                'Štěkeň',
                'Tchořovice',
                'Truskovice',
                'Třebohostice',
                'Třešovice',
                'Úlehle',
                'Únice',
                'Uzenice',
                'Uzeničky',
                'Vacovice',
                'Velká Turná',
                'Vodňany',
                'Volenice',
                'Volyně',
                'Záboří',
                'Zahorčice',
                'Zvotoky'



            ]

            break;

        case 'Tábor':

            cities=[
                'Balkova Lhota',
                'Bečice',
                'Bechyně',
                'Běleč',
                'Borkovice',
                'Borotín',
                'Bradáčov',
                'Březnice',
                'Budislav',
                'Černýšovice',
                'Dírná',
                'Dlouhá Lhota',
                'Dobronice u Bechyně',
                'Dolní Hořice',
                'Dolní Hrachovice',
                'Drahov',
                'Dráchov',
                'Dražice',
                'Dražičky',
                'Drhovice',
                'Haškovcova Lhota',
                'Hlasivo',
                'Hlavatce',
                'Hodětín',
                'Hodonice',
                'Chotěmice',
                'Chotoviny',
                'Choustník',
                'Chrbonín',
                'Chýnov',
                'Jedlany',
                'Jistebnice',
                'Katov',
                'Klenovice',
                'Komárov',
                'Košice',
                'Košín',
                'Krátošice',
                'Krtov',
                'Libějice',
                'Lom',
                'Malšice',
                'Mažice',
                'Meziříčí',
                'Mezná',
                'Mladá Vožice',
                'Mlýny',
                'Myslkovice',
                'Nadějkov',
                'Nasavrky',
                'Nemyšl',
                'Nová Ves u Chýnova',
                'Nová Ves u Mladé Vožice',
                'Oldřichov',
                'Opařany',
                'Planá nad Lužnicí',
                'Pohnánec',
                'Pohnání',
                'Pojbuky',
                'Přehořov',
                'Psárov',
                'Radenín',
                'Radětice',
                'Radimovice u Tábora',
                'Radimovice u Želče',
                'Radkov',
                'Rataje',
                'Ratibořské Hory',
                'Rodná',
                'Roudná',
                'Řemíčov',
                'Řepeč',
                'Řípec',
                'Sedlečko u Soběslavě',
                'Sezimovo Ústí',
                'Skalice',
                'Skopytce',
                'Skrýchov u Malšic',
                'Slapsko',
                'Slapy',
                'Smilovy Hory',
                'Soběslav',
                'Stádlec',
                'Sudoměřice u Bechyně',
                'Sudoměřice u Tábora',
                'Sviny',
                'Svrabov',
                'Šebířov',
                'Tábor',
                'Třebějice',
                'Tučapy',
                'Turovec',
                'Ústrašice',
                'Val',
                'Vesce',
                'Veselí nad Lužnicí',
                'Vilice',
                'Vlastiboř',
                'Vlčeves',
                'Vlkov',
                'Vodice',
                'Zadní Střítež',
                'Záhoří',
                'Zálší',
                'Zhoř u Mladé Vožice',
                'Zhoř u Tábora',
                'Zlukov',
                'Zvěrotice',
                'Želeč',
                'Žíšov'


            ]

            break;

        case 'Domažlice':
            cities=[
                'Babylon',
                'Bělá nad Radbuzou',
                'Blížejov',
                'Brnířov',
                'Čermná',
                'Česká Kubice',
                'Díly',
                'Domažlice',
                'Drahotín',
                'Draženov',
                'Hlohová',
                'Hlohovčice',
                'Hora Svatého Václava',
                'Horšovský Týn',
                'Hostouň',
                'Hradiště',
                'Hvožďany',
                'Chocomyšl',
                'Chodov',
                'Chodská Lhota',
                'Chrastavice',
                'Kanice',
                'Kaničky',
                'Kdyně',
                'Klenčí pod Čerchovem',
                'Koloveč',
                'Kout na Šumavě',
                'Křenovy',
                'Libkov',
                'Loučim',
                'Luženičky',
                'Meclov',
                'Mezholezy',
                'Milavče',
                'Mířkov',
                'Mnichov',
                'Močerady',
                'Mrákov',
                'Mutěnín',
                'Nemanice',
                'Němčice',
                'Nevolice',
                'Nová Ves',
                'Nový Kramolín',
                'Osvračín',
                'Otov',
                'Pařezov',
                'Pasečnice',
                'Pec',
                'Pelechy',
                'Poběžovice',
                'Pocinovice',
                'Poděvousy',
                'Postřekov',
                'Puclice',
                'Rybník',
                'Semněvice',
                'Spáňov',
                'Srbice',
                'Srby',
                'Staňkov',
                'Stráž',
                'Tlumačov',
                'Trhanov',
                'Úboč',
                'Újezd',
                'Únějovice',
                'Úsilov',
                'Velký Malahov',
                'Vidice',
                'Vlkanov',
                'Všepadly',
                'Všeruby',
                'Zahořany',
                'Ždánov'


            ]

            break;

        case 'Klatovy':
            cities=[
                'Běhařov',
                'Běšiny',
                'Bezděkov',
                'Biřkov',
                'Bolešiny',
                'Břežany',
                'Budětice',
                'Bukovník',
                'Čachrov',
                'Černíkov',
                'Červené Poříčí',
                'Číhaň',
                'Čímice',
                'Dešenice',
                'Dlažov',
                'Dlouhá Ves',
                'Dobršín',
                'Dolany',
                'Domoraz',
                'Dražovice',
                'Frymburk',
                'Hamry',
                'Hartmanice',
                'Hejná',
                'Hlavňovice',
                'Hnačov',
                'Horažďovice',
                'Horská Kvilda',
                'Hrádek',
                'Hradešice',
                'Chanovice',
                'Chlistov',
                'Chudenice',
                'Chudenín',
                'Janovice nad Úhlavou',
                'Javor',
                'Ježovy',
                'Kašperské Hory',
                'Kejnice',
                'Klatovy',
                'Klenová',
                'Kolinec',
                'Kovčín',
                'Křenice',
                'Kvášňovice',
                'Lomec',
                'Malý Bor',
                'Maňovice',
                'Měčín',
                'Mezihoří',
                'Mlýnské Struhadlo',
                'Modrava',
                'Mochtín',
                'Mokrosuky',
                'Myslív',
                'Myslovice',
                'Nalžovské Hory',
                'Nehodiv',
                'Nezamyslice',
                'Nezdice na Šumavě',
                'Nýrsko',
                'Obytce',
                'Olšany',
                'Ostřetice',
                'Pačejov',
                'Petrovice u Sušice',
                'Plánice',
                'Podmokly',
                'Poleň',
                'Prášily',
                'Předslav',
                'Rabí',
                'Rejštejn',
                'Slatina',
                'Soběšice',
                'Srní',
                'Strašín',
                'Strážov',
                'Sušice',
                'Svéradice',
                'Švihov',
                'Tužice',
                'Týnec',
                'Újezd u Plánice',
                'Velhartice',
                'Velké Hydčice',
                'Velký Bor',
                'Vrhaveč',
                'Vřeskovice',
                'Zavlekov',
                'Zborovy',
                'Železná Ruda',
                'Žihobce',
                'Žichovice'


            ]

            break;

        case 'Plzeň-jih':
            cities=[
                'Blovice',
                'Bolkov',
                'Borovno',
                'Borovy',
                'Buková',
                'Bukovec',
                'Čečovice',
                'Černovice',
                'Čižice',
                'Čížkov',
                'Čmelíny',
                'Dnešice',
                'Dobřany',
                'Dolce',
                'Dolní Lukavice',
                'Drahkov',
                'Holýšov',
                'Honezovice',
                'Horní Kamenice',
                'Horní Lukavice',
                'Horšice',
                'Hradec',
                'Hradiště',
                'Chlum',
                'Chlumčany',
                'Chlumy',
                'Chocenice',
                'Chotěšov',
                'Jarov',
                'Kasejovice',
                'Kbel',
                'Klášter',
                'Kotovice',
                'Kozlovice',
                'Kramolín',
                'Kvíčovice',
                'Letiny',
                'Lisov',
                'Líšina',
                'Louňová',
                'Lužany',
                'Měcholupy',
                'Merklín',
                'Mileč',
                'Milínov',
                'Míšov',
                'Mladý Smolivec',
                'Mohelnice',
                'Nebílovy',
                'Nekvasovy',
                'Nepomuk',
                'Netunice',
                'Neuměř',
                'Neurazy',
                'Nezdice',
                'Nezdřev',
                'Nová Ves',
                'Nové Mitrovice',
                'Oplot',
                'Oselce',
                'Otěšice',
                'Polánka',
                'Prádlo',
                'Předenice',
                'Přestavlky',
                'Přeštice',
                'Příchovice',
                'Ptenín',
                'Radkovice',
                'Roupov',
                'Řenče',
                'Seč',
                'Sedliště',
                'Skašov',
                'Soběkury',
                'Spálené Poříčí',
                'Srby',
                'Stod',
                'Střelice',
                'Střížovice',
                'Štěnovice',
                'Štichov',
                'Tojice',
                'Třebčice',
                'Týniště',
                'Únětice',
                'Útušice',
                'Ves Touškov',
                'Vlčí',
                'Vlčtejn',
                'Vrčeň',
                'Vstiš',
                'Všekary',
                'Zdemyslice',
                'Zemětice',
                'Žákava',
                'Ždírec',
                'Žinkovy',
                'Životice'


            ]

            break;

        case 'Plzeň-město':
            cities=[
                'Dýšina',
                'Chrást',
                'Chválenice',
                'Kyšice',
                'Letkov',
                'Lhůta',
                'Losiná',
                'Mokrouše',
                'Nezbavětice',
                'Nezvěstice',
                'Plzeň',
                'Starý Plzenec',
                'Šťáhlavy',
                'Štěnovický Borek',
                'Tymákov'


            ]

            break;

        case 'Plzeň-sever':
            cities=[
                'Bdeněves',
                'Bezvěrov',
                'Bílov',
                'Blatnice',
                'Blažim',
                'Bohy',
                'Brodeslavy',
                'Bučí',
                'Čeminy',
                'Černíkovice',
                'Čerňovice',
                'Česká Bříza',
                'Dobříč',
                'Dolany',
                'Dolní Bělá',
                'Dolní Hradiště',
                'Dražeň',
                'Druztová',
                'Heřmanova Huť',
                'Hlince',
                'Hněvnice',
                'Holovousy',
                'Horní Bělá',
                'Horní Bříza',
                'Hromnice',
                'Hvozd',
                'Chotíkov',
                'Chříč',
                'Jarov',
                'Kaceřov',
                'Kaznějov',
                'Kbelany',
                'Kočín',
                'Kopidlo',
                'Koryta',
                'Kozojedy',
                'Kozolupy',
                'Kožlany',
                'Kralovice',
                'Krašovice',
                'Krsy',
                'Křelovice',
                'Kunějovice',
                'Ledce',
                'Líně',
                'Líšťany',
                'Líté',
                'Lochousice',
                'Loza',
                'Manětín',
                'Město Touškov',
                'Mladotice',
                'Mrtník',
                'Myslinka',
                'Nadryby',
                'Nečtiny',
                'Nekmíř',
                'Nevřeň',
                'Nýřany',
                'Obora',
                'Ostrov u Bezdružic',
                'Pastuchovice',
                'Pernarec',
                'Pláně',
                'Plasy',
                'Plešnice',
                'Pňovany',
                'Potvorov',
                'Přehýšov',
                'Příšov',
                'Rochlov',
                'Rybnice',
                'Sedlec',
                'Slatina',
                'Studená',
                'Štichovice',
                'Tatiná',
                'Tis u Blatna',
                'Tlučná',
                'Trnová',
                'Třemošná',
                'Úherce',
                'Újezd nade Mží',
                'Úlice',
                'Úněšov',
                'Úterý',
                'Vejprnice',
                'Velečín',
                'Vochov',
                'Všehrdy',
                'Všeruby',
                'Výrov',
                'Vysoká Libyně',
                'Zahrádka',
                'Zbůch',
                'Zruč-Senec',
                'Žihle',
                'Žilov'


            ]

            break;



        case 'Rokycany':
            cities=[
                'Bezděkov',
                'Břasy',
                'Březina',
                'Bujesily',
                'Bušovice',
                'Cekov',
                'Čilá',
                'Dobřív',
                'Drahoňův Újezd',
                'Ejpovice',
                'Hlohovice',
                'Holoubkov',
                'Hrádek',
                'Hradiště',
                'Hůrky',
                'Cheznovice',
                'Chlum',
                'Chomle',
                'Kakejcov',
                'Kamenec',
                'Kamenný Újezd',
                'Kařez',
                'Kařízek',
                'Klabava',
                'Kladruby',
                'Kornatice',
                'Lhota pod Radčem',
                'Lhotka u Radnic',
                'Liblín',
                'Líšná',
                'Litohlavy',
                'Medový Újezd',
                'Mešno',
                'Mirošov',
                'Mlečice',
                'Mýto',
                'Němčovice',
                'Nevid',
                'Osek',
                'Ostrovec-Lhotka',
                'Plískov',
                'Podmokly',
                'Příkosice',
                'Přívětice',
                'Radnice',
                'Raková',
                'Rokycany',
                'Sebečice',
                'Sirá',
                'Skomelno',
                'Skořice',
                'Smědčice',
                'Strašice',
                'Svojkovice',
                'Štítov',
                'Těně',
                'Terešov',
                'Těškov',
                'Trokavec',
                'Týček',
                'Újezd u Svatého Kříže',
                'Vejvanov',
                'Veselá',
                'Vísky',
                'Volduchy',
                'Všenice',
                'Zbiroh',
                'Zvíkovec'


            ]

            break;

        case 'Tachov':
            cities=[
                'Benešovice',
                'Bezdružice',
                'Bor',
                'Brod nad Tichou',
                'Broumov',
                'Cebiv',
                'Ctiboř',
                'Částkov',
                'Černošín',
                'Dlouhý Újezd',
                'Erpužice',
                'Halže',
                'Horní Kozolupy',
                'Hošťka',
                'Chodová Planá',
                'Chodský Újezd',
                'Kladruby',
                'Kočov',
                'Kokašice',
                'Konstantinovy Lázně',
                'Kostelec',
                'Kšice',
                'Lesná',
                'Lestkov',
                'Lom u Tachova',
                'Milíře',
                'Obora',
                'Olbramov',
                'Ošelín',
                'Planá',
                'Prostiboř',
                'Přimda',
                'Rozvadov',
                'Skapce',
                'Staré Sedliště',
                'Staré Sedlo',
                'Stráž',
                'Stříbro',
                'Studánka',
                'Sulislav',
                'Svojšín',
                'Sytno',
                'Tachov',
                'Tisová',
                'Trpísty',
                'Třemešné',
                'Únehle',
                'Vranov',
                'Zadní Chodov',
                'Záchlumí',
                'Zhoř'


            ]

            break;

        case 'Cheb':
            cities=[
                'Aš',
                'Dolní Žandov',
                'Drmoul',
                'Františkovy Lázně',
                'Hazlov',
                'Hranice',
                'Cheb',
                'Krásná',
                'Křižovatka',
                'Lázně Kynžvart',
                'Libá',
                'Lipová',
                'Luby',
                'Mariánské Lázně',
                'Milhostov',
                'Milíkov',
                'Mnichov',
                'Nebanice',
                'Nový Kostel',
                'Odrava',
                'Okrouhlá',
                'Ovesné Kladruby',
                'Plesná',
                'Podhradí',
                'Pomezí nad Ohří',
                'Poustka',
                'Prameny',
                'Skalná',
                'Stará Voda',
                'Teplá',
                'Trstěnice',
                'Třebeň',
                'Tři Sekery',
                'Tuřany',
                'Valy',
                'Velká Hleďsebe',
                'Velký Luh',
                'Vlkovice',
                'Vojtanov',
                'Zádub-Závišín'


            ]

            break;

        case 'Karlovy Vary':
            cities=[
                'Abertamy',
                'Andělská Hora',
                'Bečov nad Teplou',
                'Bochov',
                'Boží Dar',
                'Božičany',
                'Bražec',
                'Březová',
                'Černava',
                'Čichalov',
                'Dalovice',
                'Děpoltovice',
                'Doupovské Hradiště',
                'Hájek',
                'Horní Blatná',
                'Hory',
                'Hroznětín',
                'Chodov',
                'Chyše',
                'Jáchymov',
                'Jenišov',
                'Karlovy Vary',
                'Kolová',
                'Krásné Údolí',
                'Krásný Les',
                'Kyselka',
                'Merklín',
                'Mírová',
                'Nejdek',
                'Nová Role',
                'Nové Hamry',
                'Ostrov',
                'Otovice',
                'Otročín',
                'Pernink',
                'Pila',
                'Potůčky',
                'Pšov',
                'Sadov',
                'Smolné Pece',
                'Stanovice',
                'Stráž nad Ohří',
                'Stružná',
                'Šemnice',
                'Štědrá',
                'Teplička',
                'Toužim',
                'Útvina',
                'Valeč',
                'Velichov',
                'Verušičky',
                'Vojkovice',
                'Vrbice',
                'Vysoká Pec',
                'Žlutice'



            ]

            break;

        case 'Sokolov':
            cities=[
                'Březová',
                'Bublava',
                'Bukovany',
                'Citice',
                'Dasnice',
                'Dolní Nivy',
                'Dolní Rychnov',
                'Habartov',
                'Horní Slavkov',
                'Chlum Svaté Maří',
                'Chodov',
                'Jindřichovice',
                'Josefov',
                'Kaceřov',
                'Krajková',
                'Královské Poříčí',
                'Kraslice',
                'Krásno',
                'Kynšperk nad Ohří',
                'Libavské Údolí',
                'Loket',
                'Lomnice',
                'Nová Ves',
                'Nové Sedlo',
                'Oloví',
                'Přebuz',
                'Rotava',
                'Rovná',
                'Sokolov',
                'Staré Sedlo',
                'Stříbrná',
                'Svatava',
                'Šabina',
                'Šindelová',
                'Tatrovice',
                'Těšovice',
                'Vintířov',
                'Vřesová'


            ]

            break;

        case 'Děčín':

            cities=[
                'Arnoltice',
                'Benešov nad Ploučnicí',
                'Bynovec',
                'Česká Kamenice',
                'Děčín',
                'Dobkovice',
                'Dobrná',
                'Dolní Habartice',
                'Dolní Podluží',
                'Dolní Poustevna',
                'Doubice',
                'Františkov nad Ploučnicí',
                'Heřmanov',
                'Horní Habartice',
                'Horní Podluží',
                'Hřensko',
                'Huntířov',
                'Chřibská',
                'Janov',
                'Janská',
                'Jetřichovice',
                'Jílové',
                'Jiřetín pod Jedlovou',
                'Jiříkov',
                'Kámen',
                'Krásná Lípa',
                'Kunratice',
                'Kytlice',
                'Labská Stráň',
                'Lipová',
                'Lobendava',
                'Ludvíkovice',
                'Malá Veleň',
                'Malšovice',
                'Markvartice',
                'Merboltice',
                'Mikulášovice',
                'Rumburk',
                'Růžová',
                'Rybniště',
                'Srbská Kamenice',
                'Staré Křečany',
                'Starý Šachov',
                'Šluknov',
                'Těchlovice',
                'Valkeřice',
                'Varnsdorf',
                'Velká Bukovina',
                'Velký Šenov',
                'Verneřice',
                'Veselé',
                'Vilémov'


            ]

            break;


        case 'Chomutov':
            cities=[
                'Bílence',
                'Blatno',
                'Boleboř',
                'Březno',
                'Černovice',
                'Domašín',
                'Droužkovice',
                'Hora Svatého Šebestiána',
                'Hrušovany',
                'Chbany',
                'Chomutov',
                'Jirkov',
                'Kadaň',
                'Kalek',
                'Klášterec nad Ohří',
                'Kovářská',
                'Kryštofovy Hamry',
                'Křimov',
                'Libědice',
                'Loučná pod Klínovcem',
                'Málkov',
                'Mašťov',
                'Měděnec',
                'Místo',
                'Nezabylice',
                'Okounov',
                'Otvice',
                'Perštejn',
                'Pesvice',
                'Pětipsy',
                'Račetice',
                'Radonice',
                'Rokle',
                'Spořice',
                'Strupčice',
                'Údlice',
                'Vejprty',
                'Veliká Ves',
                'Vilémov',
                'Vrskmaň',
                'Všehrdy',
                'Všestudy',
                'Výsluní',
                'Vysoká Pec'


            ]

            break;

        case 'Litoměřice':
            cities=[
                'Bechlín',
                'Bohušovice nad Ohří',
                'Brňany',
                'Brozany nad Ohří',
                'Brzánky',
                'Bříza',
                'Budyně nad Ohří',
                'Býčkovice',
                'Ctiněves',
                'Černěves',
                'Černiv',
                'Černouček',
                'Čížkovice',
                'Děčany',
                'Dlažkovice',
                'Dobříň',
                'Doksany',
                'Dolánky nad Ohří',
                'Drahobuz',
                'Dušníky',
                'Evaň',
                'Hlinná',
                'Horní Beřkovice',
                'Horní Řepčice',
                'Hoštka',
                'Hrobce',
                'Chodouny',
                'Chodovlice',
                'Chotěšov',
                'Chotiměř',
                'Chotiněves',
                'Chudoslavice',
                'Jenčice',
                'Kamýk',
                'Keblice',
                'Klapý',
                'Kleneč',
                'Kostomlaty pod Řípem',
                'Krabčice',
                'Křesín',
                'Křešice',
                'Kyškovice',
                'Levín',
                'Lhotka nad Labem',
                'Liběšice',
                'Libkovice pod Řípem',
                'Libochovany',
                'Libochovice',
                'Libotenice',
                'Litoměřice',
                'Lkáň',
                'Lovečkovice',
                'Lovosice',
                'Lukavec',
                'Malé Žernoseky',
                'Malíč',
                'Martiněves',
                'Michalovice',
                'Miřejovice',
                'Mlékojedy',
                'Mnetěš',
                'Mšené-lázně',
                'Nové Dvory',
                'Oleško',
                'Píšťany',
                'Ploskovice',
                'Podsedice',
                'Polepy',
                'Prackovice nad Labem',
                'Přestavlky',
                'Račice',
                'Račiněves',
                'Radovesice',
                'Rochov',
                'Roudnice nad Labem',
                'Sedlec',
                'Siřejovice',
                'Slatina',
                'Snědovice',
                'Staňkovice',
                'Straškov-Vodochody',
                'Sulejovice',
                'Štětí',
                'Terezín',
                'Travčice',
                'Trnovany',
                'Třebenice',
                'Třebívlice',
                'Třebušín',
                'Úpohlavy',
                'Úštěk',
                'Vědomice',
                'Velemín',
                'Velké Žernoseky',
                'Vchynice',
                'Vlastislav',
                'Vražkov',
                'Vrbice',
                'Vrbičany',
                'Vrutice',
                'Záluží',
                'Žabovřesky nad Ohří',
                'Žalhostice',
                'Židovice',
                'Žitenice'


            ]

            break;

        case 'Louny':
            cities=[
                'Bitozeves',
                'Blatno',
                'Blažim',
                'Blšany',
                'Blšany u Loun',
                'Brodec',
                'Břvany',
                'Cítoliby',
                'Čeradice',
                'Černčice',
                'Deštnice',
                'Dobroměřice',
                'Domoušice',
                'Holedeč',
                'Hříškov',
                'Hřivice',
                'Chlumčany',
                'Chožov',
                'Chraberce',
                'Jimlín',
                'Koštice',
                'Kozly',
                'Krásný Dvůr',
                'Kryry',
                'Lenešice',
                'Libčeves',
                'Liběšice',
                'Libočany',
                'Libořice',
                'Lipno',
                'Lišany',
                'Líšťany',
                'Louny',
                'Lubenec',
                'Měcholupy',
                'Nepomyšl',
                'Nová Ves',
                'Nové Sedlo',
                'Obora',
                'Očihov',
                'Opočno',
                'Panenský Týnec',
                'Peruc',
                'Petrohrad',
                'Pnětluky',
                'Počedělice',
                'Podbořanský Rohozec',
                'Podbořany',
                'Postoloprty',
                'Raná',
                'Ročov',
                'Slavětín',
                'Smolnice',
                'Staňkovice',
                'Toužetín',
                'Tuchořice',
                'Úherce',
                'Velemyšleves',
                'Veltěže',
                'Vinařice',
                'Vrbno nad Lesy',
                'Vroutek',
                'Vršovice',
                'Výškov',
                'Zálužice',
                'Zbrašín',
                'Žatec',
                'Želkovice',
                'Žerotín',
                'Žiželice'


            ]

            break;


        case 'Most':
            cities=[
                'Bečov',
                'Bělušice',
                'Braňany',
                'Brandov',
                'Český Jiřetín',
                'Havraň',
                'Hora Svaté Kateřiny',
                'Horní Jiřetín',
                'Klíny',
                'Korozluky',
                'Lišnice',
                'Litvínov',
                'Lom',
                'Louka u Litvínova',
                'Lužice',
                'Malé Březno',
                'Mariánské Radčice',
                'Meziboří',
                'Most',
                'Nová Ves v Horách',
                'Obrnice',
                'Patokryje',
                'Polerady',
                'Skršín',
                'Volevčice',
                'Želenice'


            ]

            break;

        case 'Teplice':
            cities=[
                'Bílina',
                'Bořislav',
                'Bystřany',
                'Bžany',
                'Dubí',
                'Duchcov',
                'Háj u Duchcova',
                'Hostomice',
                'Hrob',
                'Hrobčice',
                'Jeníkov',
                'Kladruby',
                'Kostomlaty pod Milešovkou',
                'Košťany',
                'Krupka',
                'Lahošť',
                'Ledvice',
                'Lukov',
                'Měrunice',
                'Mikulov',
                'Modlany',
                'Moldava',
                'Novosedlice',
                'Ohníč',
                'Osek',
                'Proboštov',
                'Rtyně nad Bílinou',
                'Srbice',
                'Světec',
                'Teplice',
                'Újezdeček',
                'Zabrušany',
                'Žalany',
                'Žim'


            ]

            break;

        case 'Ústí nad Labem':
            cities=[
                'Dolní Zálezly',
                'Habrovany',
                'Homole u Panny',
                'Chabařovice',
                'Chlumec',
                'Chuderov',
                'Libouchec',
                'Malé Březno',
                'Malečov',
                'Petrovice',
                'Povrly',
                'Přestanov',
                'Ryjice',
                'Řehlovice',
                'Stebno',
                'Tašov',
                'Telnice',
                'Tisá',
                'Trmice',
                'Ústí nad Labem',
                'Velké Březno',
                'Velké Chvojno',
                'Zubrnice'


            ]

            break;


        case 'Česká Lípa':
            cities=[
                'Bezděz',
                'Blatce',
                'Blíževedly',
                'Bohatice',
                'Brniště',
                'Cvikov',
                'Česká Lípa',
                'Doksy',
                'Dubá',
                'Dubnice',
                'Hamr na Jezeře',
                'Holany',
                'Horní Libchava',
                'Horní Police',
                'Chlum',
                'Chotovice',
                'Jestřebí',
                'Kamenický Šenov',
                'Kozly',
                'Kravaře',
                'Krompach',
                'Kunratice u Cvikova',
                'Kvítkov',
                'Luka',
                'Mařenice',
                'Mimoň',
                'Noviny pod Ralskem',
                'Nový Bor',
                'Nový Oldřichov',
                'Okna',
                'Okrouhlá',
                'Pertoltice pod Ralskem',
                'Polevsko',
                'Provodín',
                'Prysk',
                'Radvanec',
                'Ralsko',
                'Skalice u České Lípy',
                'Skalka u Doks',
                'Sloup v Čechách',
                'Slunečná',
                'Sosnová',
                'Stráž pod Ralskem',
                'Stružnice',
                'Stvolínky',
                'Svojkov',
                'Svor',
                'Tachov',
                'Tuhaň',
                'Velenice',
                'Velký Valtinov',
                'Volfartice',
                'Vrchovany',
                'Zahrádky',
                'Zákupy',
                'Žandov',
                'Ždírec'


            ]

            break;

        case 'Jablonec nad Nisou':
            cities=[
                'Albrechtice v Jizerských horách',
                'Bedřichov',
                'Dalešice',
                'Desná',
                'Držkov',
                'Frýdštejn',
                'Harrachov',
                'Jablonec nad Nisou',
                'Janov nad Nisou',
                'Jenišovice',
                'Jílové u Držkova',
                'Jiřetín pod Bukovou',
                'Josefův Důl',
                'Koberovy',
                'Kořenov',
                'Líšný',
                'Loužnice',
                'Lučany nad Nisou',
                'Malá Skála',
                'Maršovice',
                'Nová Ves nad Nisou',
                'Pěnčín',
                'Plavy',
                'Pulečný',
                'Radčice',
                'Rádlo',
                'Rychnov u Jablonce nad Nisou',
                'Skuhrov',
                'Smržovka',
                'Tanvald',
                'Velké Hamry',
                'Vlastiboř',
                'Zásada',
                'Zlatá Olešnice',
                'Železný Brod'


            ]

            break;

        case 'Liberec':
            cities=[
                'Bílá',
                'Bílý Kostel nad Nisou',
                'Bílý Potok',
                'Bulovka',
                'Cetenov',
                'Černousy',
                'Český Dub',
                'Čtveřín',
                'Dětřichov',
                'Dlouhý Most',
                'Dolní Řasnice',
                'Frýdlant',
                'Habartice',
                'Hejnice',
                'Heřmanice',
                'Hlavice',
                'Hodkovice nad Mohelkou',
                'Horní Řasnice',
                'Hrádek nad Nisou',
                'Chotyně',
                'Chrastava',
                'Jablonné v Podještědí',
                'Janovice v Podještědí',
                'Janův Důl',
                'Jeřmanice',
                'Jindřichovice pod Smrkem',
                'Kobyly',
                'Krásný Les',
                'Kryštofovo Údolí',
                'Křižany',
                'Kunratice',
                'Lázně Libverda',
                'Lažany',
                'Liberec',
                'Mníšek',
                'Nová Ves',
                'Nové Město pod Smrkem',
                'Oldřichov v Hájích',
                'Osečná',
                'Paceřice',
                'Pěnčín',
                'Pertoltice',
                'Proseč pod Ještědem',
                'Příšovice',
                'Radimovice',
                'Raspenava',
                'Rynoltice',
                'Soběslavice',
                'Stráž nad Nisou',
                'Světlá pod Ještědem',
                'Svijanský Újezd',
                'Svijany',
                'Sychrov',
                'Šimonovice',
                'Višňová',
                'Vlastibořice',
                'Všelibice',
                'Zdislava',
                'Žďárek'


            ]

            break;


        case 'Semily':
            cities=[
                'Bělá',
                'Benecko',
                'Benešov u Semil',
                'Bozkov',
                'Bradlecká Lhota',
                'Bukovina u Čisté',
                'Bystrá nad Jizerou',
                'Čistá u Horek',
                'Háje nad Jizerou',
                'Holenice',
                'Horka u Staré Paky',
                'Horní Branná',
                'Hrubá Skála',
                'Chuchelna',
                'Jablonec nad Jizerou',
                'Jesenný',
                'Jestřabí v Krkonoších',
                'Jilemnice',
                'Kacanovy',
                'Karlovice',
                'Klokočí',
                'Košťálov',
                'Kruh',
                'Ktová',
                'Levínská Olešnice',
                'Libštát',
                'Lomnice nad Popelkou',
                'Loučky',
                'Martinice v Krkonoších',
                'Mírová pod Kozákovem',
                'Modřišice',
                'Mříčná',
                'Nová Ves nad Popelkou',
                'Ohrazenice',
                'Olešnice',
                'Paseky nad Jizerou',
                'Peřimov',
                'Poniklá',
                'Přepeře',
                'Příkrý',
                'Radostná pod Kozákovem',
                'Rakousy',
                'Rokytnice nad Jizerou',
                'Roprachtice',
                'Rovensko pod Troskami',
                'Roztoky u Jilemnice',
                'Roztoky u Semil',
                'Semily',
                'Slaná',
                'Stružinec',
                'Studenec',
                'Svojek',
                'Syřenov',
                'Tatobity',
                'Troskovice',
                'Turnov',
                'Veselá',
                'Víchová nad Jizerou',
                'Vítkovice',
                'Všeň',
                'Vyskeř',
                'Vysoké nad Jizerou',
                'Záhoří',
                'Žernov'


            ]

            break;

        case '':
            cities=[

            ]

            break;

        case '':
            cities=[

            ]

            break;





    }





    return cities;




}



















export default getDistrictsArray
